In [25]:
import numpy as np

In [26]:
data = np.random.random(10000)

In [27]:
data.shape = 10000, 1

In [28]:
labels = np.array(data >= .5, dtype = int)

In [29]:
data

array([[0.73224421],
       [0.38964888],
       [0.96838599],
       ...,
       [0.65481208],
       [0.36619629],
       [0.10591216]])

In [30]:
labels

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [0]])

In [31]:
from keras import Sequential
from keras.layers import Dense

In [32]:
model = Sequential(
  [
    Dense(units=8, input_shape=(1,), activation = 'relu'),
    Dense(units=2, activation='softmax')
  ]
)

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 8)                 16        
                                                                 
 dense_5 (Dense)             (None, 2)                 18        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [34]:
"""
Compile the model
"""
model.compile(
  loss='sparse_categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)


In [19]:
# Train the model

model.fit(
  x=data,
  y=labels,
  epochs=10,
  verbose=2
)

Epoch 1/10
313/313 - 1s - loss: 0.5514 - accuracy: 0.7577 - 715ms/epoch - 2ms/step
Epoch 2/10
313/313 - 0s - loss: 0.3920 - accuracy: 0.9133 - 188ms/epoch - 601us/step
Epoch 3/10
313/313 - 0s - loss: 0.2817 - accuracy: 0.9591 - 188ms/epoch - 599us/step
Epoch 4/10
313/313 - 0s - loss: 0.2133 - accuracy: 0.9758 - 188ms/epoch - 599us/step
Epoch 5/10
313/313 - 0s - loss: 0.1698 - accuracy: 0.9844 - 192ms/epoch - 613us/step
Epoch 6/10
313/313 - 0s - loss: 0.1403 - accuracy: 0.9896 - 192ms/epoch - 612us/step
Epoch 7/10
313/313 - 0s - loss: 0.1194 - accuracy: 0.9928 - 188ms/epoch - 601us/step
Epoch 8/10
313/313 - 0s - loss: 0.1035 - accuracy: 0.9945 - 188ms/epoch - 599us/step
Epoch 9/10
313/313 - 0s - loss: 0.0915 - accuracy: 0.9949 - 189ms/epoch - 602us/step
Epoch 10/10
313/313 - 0s - loss: 0.0818 - accuracy: 0.9959 - 191ms/epoch - 609us/step


In [20]:
# Testing the model

test_data = np.array([0, 0.2, 0.4, 0.6, 0.8, 1])
predictions = model.predict(test_data)

1/1 [==============================] - 0s 55ms/step


In [22]:
predictions
print(np.argmax(predictions, axis=1))

[0 0 0 1 1 1]


In [35]:
""" 
Valudating the model during training
"""
model.fit(
  x=data,
  y=labels,
  epochs=10,
  verbose=2,
  validation_split=.1
)


Epoch 1/10
282/282 - 1s - loss: 0.5344 - accuracy: 0.7731 - val_loss: 0.4412 - val_accuracy: 0.8990 - 636ms/epoch - 2ms/step
Epoch 2/10
282/282 - 0s - loss: 0.3626 - accuracy: 0.9318 - val_loss: 0.2905 - val_accuracy: 0.9590 - 214ms/epoch - 760us/step
Epoch 3/10
282/282 - 0s - loss: 0.2437 - accuracy: 0.9737 - val_loss: 0.2048 - val_accuracy: 0.9850 - 213ms/epoch - 757us/step
Epoch 4/10
282/282 - 0s - loss: 0.1794 - accuracy: 0.9870 - val_loss: 0.1584 - val_accuracy: 0.9910 - 213ms/epoch - 757us/step
Epoch 5/10
282/282 - 0s - loss: 0.1428 - accuracy: 0.9926 - val_loss: 0.1307 - val_accuracy: 0.9980 - 205ms/epoch - 729us/step
Epoch 6/10
282/282 - 0s - loss: 0.1200 - accuracy: 0.9952 - val_loss: 0.1124 - val_accuracy: 0.9990 - 209ms/epoch - 743us/step
Epoch 7/10
282/282 - 0s - loss: 0.1042 - accuracy: 0.9970 - val_loss: 0.0986 - val_accuracy: 0.9940 - 206ms/epoch - 732us/step
Epoch 8/10
282/282 - 0s - loss: 0.0927 - accuracy: 0.9963 - val_loss: 0.0888 - val_accuracy: 0.9990 - 211ms/epoch